/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Classes.Jogo;
import Classes.Quadradao;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Foltran
 */
public class Principal extends javax.swing.JFrame {

    private Jogo jg;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.jg = new Jogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_grupo1 = new javax.swing.ButtonGroup();
        panel_puzzle = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        panel_embaralhar = new javax.swing.JPanel();
        button_embaralhar = new javax.swing.JButton();
        label_embaralhar = new javax.swing.JLabel();
        input_embaralhar = new javax.swing.JTextField();
        panel_ordenar = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        panel_puzzle.setBackground(new java.awt.Color(153, 153, 153));
        panel_puzzle.setBorder(javax.swing.BorderFactory.createTitledBorder("Puzzle"));

        label1.setBackground(new java.awt.Color(200, 30, 30));
        label1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("1");
        label1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label1.setOpaque(true);

        label2.setBackground(new java.awt.Color(30, 200, 30));
        label2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label2.setText("2");
        label2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label2.setOpaque(true);

        label3.setBackground(new java.awt.Color(30, 30, 200));
        label3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label3.setText("3");
        label3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label3.setOpaque(true);

        label4.setBackground(new java.awt.Color(200, 30, 200));
        label4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label4.setText("4");
        label4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label4.setOpaque(true);

        label5.setBackground(new java.awt.Color(200, 200, 30));
        label5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label5.setText("5");
        label5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label5.setOpaque(true);

        label6.setBackground(new java.awt.Color(30, 200, 200));
        label6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label6.setText("6");
        label6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label6.setOpaque(true);

        label7.setBackground(new java.awt.Color(200, 200, 200));
        label7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label7.setText("7");
        label7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label7.setOpaque(true);

        label8.setBackground(new java.awt.Color(30, 30, 30));
        label8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label8.setForeground(new java.awt.Color(200, 200, 200));
        label8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label8.setText("8");
        label8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label8.setOpaque(true);

        label9.setBackground(new java.awt.Color(153, 153, 153));
        label9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        label9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        label9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        label9.setPreferredSize(new java.awt.Dimension(17, 27));

        javax.swing.GroupLayout panel_puzzleLayout = new javax.swing.GroupLayout(panel_puzzle);
        panel_puzzle.setLayout(panel_puzzleLayout);
        panel_puzzleLayout.setHorizontalGroup(
            panel_puzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_puzzleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_puzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_puzzleLayout.createSequentialGroup()
                        .addGroup(panel_puzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_puzzleLayout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panel_puzzleLayout.createSequentialGroup()
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_puzzleLayout.createSequentialGroup()
                        .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panel_puzzleLayout.setVerticalGroup(
            panel_puzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_puzzleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_puzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_puzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_puzzleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_embaralhar.setBorder(javax.swing.BorderFactory.createTitledBorder("Embaralhar"));

        button_embaralhar.setText("Embaralhar");
        button_embaralhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_embaralharActionPerformed(evt);
            }
        });

        label_embaralhar.setText("Qtd. de Movimentos:");

        javax.swing.GroupLayout panel_embaralharLayout = new javax.swing.GroupLayout(panel_embaralhar);
        panel_embaralhar.setLayout(panel_embaralharLayout);
        panel_embaralharLayout.setHorizontalGroup(
            panel_embaralharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_embaralharLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_embaralharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_embaralharLayout.createSequentialGroup()
                        .addComponent(label_embaralhar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(input_embaralhar)
                    .addComponent(button_embaralhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_embaralharLayout.setVerticalGroup(
            panel_embaralharLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_embaralharLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_embaralhar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(input_embaralhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(button_embaralhar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_ordenar.setBorder(javax.swing.BorderFactory.createTitledBorder("Resolver"));

        rb_grupo1.add(jRadioButton1);
        jRadioButton1.setText("Random");

        rb_grupo1.add(jRadioButton2);
        jRadioButton2.setText("Heuristica 1");

        rb_grupo1.add(jRadioButton3);
        jRadioButton3.setText("Heuristica 2");

        rb_grupo1.add(jRadioButton4);
        jRadioButton4.setText("Heuristica 3");

        jButton1.setText("Resolver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_ordenarLayout = new javax.swing.GroupLayout(panel_ordenar);
        panel_ordenar.setLayout(panel_ordenarLayout);
        panel_ordenarLayout.setHorizontalGroup(
            panel_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ordenarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_ordenarLayout.setVerticalGroup(
            panel_ordenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ordenarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_puzzle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_embaralhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_puzzle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_embaralhar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_ordenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_ordenar.getAccessibleContext().setAccessibleName("Resolver");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_embaralharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_embaralharActionPerformed
        ArrayList<Integer> trocas;
        int passos = Integer.parseInt(this.input_embaralhar.getText());
        trocas = this.jg.embaralhar(passos);
        for (Integer troca : trocas) {
            animacao(troca);
        }
    }//GEN-LAST:event_button_embaralharActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<Integer> trocas = null;
        
        int cont;
        String msg = "";

        if (this.jRadioButton1.isSelected()) {
            trocas = this.jg.resolverAleatorio();
            msg = "";

        } else if (this.jRadioButton2.isSelected()) {
            cont = this.jg.heuristicaNiveis(this.jg.getQ(), 1);
            trocas = this.jg.getTrocas();
            msg = "Foram realizadas " + cont + " iterações";
           
        } else if (this.jRadioButton3.isSelected()) {

            cont = this.jg.heuristicaNiveis(this.jg.getQ(), 2);
            trocas = this.jg.getTrocas();
            msg = "Foram realizadas " + cont + " iterações";
        }else if (this.jRadioButton4.isSelected()) {

            cont = this.jg.heuristicaNiveis(this.jg.getQ(), 3);
            trocas = this.jg.getTrocas();
            msg = "Foram realizadas " + cont + " iterações";
        }

        for (Integer troca : trocas) {

            animacao(troca);
        }
        msg += "\n A solução foi encontrada com " + trocas.size() + " passos";
        JOptionPane.showMessageDialog(null, msg);


    }//GEN-LAST:event_jButton1ActionPerformed

    public void animacao(int trocas) {

        Point p;
        // this.wait(5);
        switch ((trocas + 1)) {

            case 1:
                p = this.label1.getLocation();
                this.label1.setLocation(this.label9.getLocation());
                this.label9.setLocation(p);
                break;

            case 2:
                p = this.label2.getLocation();
                this.label2.setLocation(this.label9.getLocation());
                this.label9.setLocation(p);
                break;

            case 3:
                p = this.label3.getLocation();
                this.label3.setLocation(this.label9.getLocation());
                this.label9.setLocation(p);
                break;

            case 4:
                p = this.label4.getLocation();
                this.label4.setLocation(this.label9.getLocation());
                this.label9.setLocation(p);
                break;

            case 5:
                p = this.label5.getLocation();
                this.label5.setLocation(this.label9.getLocation());
                this.label9.setLocation(p);
                break;

            case 6:
                p = this.label6.getLocation();
                this.label6.setLocation(this.label9.getLocation());
                this.label9.setLocation(p);
                break;

            case 7:
                p = this.label7.getLocation();
                this.label7.setLocation(this.label9.getLocation());
                this.label9.setLocation(p);
                break;

            case 8:
                p = this.label8.getLocation();
                this.label8.setLocation(this.label9.getLocation());
                this.label9.setLocation(p);
                break;

        }//switch

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_embaralhar;
    private javax.swing.JTextField input_embaralhar;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel label_embaralhar;
    private javax.swing.JPanel panel_embaralhar;
    private javax.swing.JPanel panel_ordenar;
    private javax.swing.JPanel panel_puzzle;
    private javax.swing.ButtonGroup rb_grupo1;
    // End of variables declaration//GEN-END:variables
}
